import type {
  MasterCvCertification,
  MasterCvEducation,
  MasterCvExperience,
  MasterCvLanguage,
  MasterCvProject,
  MasterCvSkill,
  SocialLinks,
} from "./cv-lab.schema";

// --- Personal Info ---

export const SEED_PERSONAL_INFO = {
  fullName: "Yoann Andrieux",
  headline:
    "Developpeur React Native / React / Next.js — Apps iOS/Android & SaaS web — Ex-Operations Manager (1000+ recrutements)",
  summary:
    "Developpeur mobile et web (React Native, React, Next.js, TypeScript), je concois des produits orientes usage avec un fort niveau d'exigence UX, architecture et qualite de livraison. Mon parcours initial en operations (Cyclofix) m'apporte une lecture business concrete : priorisation, execution, gestion d'equipes et fiabilite sous pression. J'interviens de la conception a la mise en production, sur des produits B2C/B2B (mobile, SaaS, PWA), avec une attention forte a la maintenabilite, la performance et la valeur metier.",
  email: "yoann.andrieux@gmail.com",
  phone: "+33 6 63 43 46 65",
  city: "Paris, France",
  hobbies: ["Musique", "Sport", "Cinema"],
  driverLicenses: ["A", "B"],
} as const;

export const SEED_SOCIAL_LINKS: SocialLinks = {
  linkedinUrl: "https://linkedin.com/in/yoann-andrieux",
  githubUrl: "https://github.com/YoannDrx",
  websiteUrl: "https://yoann-andrieux.fr",
  maltUrl: "https://malt.fr/profile/yoannandrieux",
};

// --- 20 Experiences ---

export const SEED_EXPERIENCES: MasterCvExperience[] = [
  {
    id: "exp-cupra",
    title: "Pub — Regie plateau",
    company: "CUPRA x AVNIER",
    startDate: "fevrier 2026",
    endDate: "fevrier 2026",
    current: false,
    location: "Noisy-le-Grand (93)",
    contractType: "PONCTUEL",
    remote: "ONSITE",
    description:
      "Coordination logistique et operationnelle sur un tournage publicitaire pour la collaboration CUPRA x AVNIER. Gestion du plateau en equipe de nuit, avec suivi des plannings et coordination des equipes techniques. Realisation Benjamin Marchal, DOP Lara Perrotte.",
    teamContext:
      "Production Wilders, Agence BBDO, Realisation Benjamin Marchal, DOP Lara Perrotte",
    techStack: [],
    achievements: [
      "Coordination logistique sur un tournage publicitaire de grande envergure (CUPRA x AVNIER)",
      "Gestion du plateau en equipe de nuit avec suivi rigoureux des plannings",
      "Interface entre Production Wilders et Agence BBDO",
      "Tournage sous la realisation de Benjamin Marchal, DOP Lara Perrotte",
    ],
  },
  {
    id: "exp-optic2000",
    title: "Pub — Premier assistant camera",
    company: "Optic 2000",
    startDate: "septembre 2023",
    endDate: "septembre 2023",
    current: false,
    location: "Paris",
    contractType: "PONCTUEL",
    remote: "ONSITE",
    description:
      "Premier assistant camera sur un tournage publicitaire pour Optic 2000. Preparation et gestion du materiel camera, suivi des plans sous la direction du chef operateur Julien Froment.",
    teamContext: "Chef operateur Julien Froment",
    techStack: [],
    achievements: [
      "Premier assistant camera sur un tournage publicitaire national",
      "Preparation et gestion du materiel camera (objectifs, filtres, supports)",
      "Coordination avec le chef operateur Julien Froment pour le suivi des plans",
      "Gestion des changements de configuration entre les sequences",
    ],
  },
  {
    id: "exp-oppenheimer",
    title: "Assistant projectionniste — Avant-premiere 70mm",
    company: "Grand Rex",
    startDate: "juillet 2023",
    endDate: "juillet 2023",
    current: false,
    location: "Paris",
    contractType: "PONCTUEL",
    remote: "ONSITE",
    description:
      "Assistant projectionniste pour l'avant-premiere et l'exploitation du film Oppenheimer de Christopher Nolan en pellicule 70mm au Grand Rex. Premiere projection publique 70mm au Grand Rex depuis 1989 (Indiana Jones). Installation et operation d'une cabine de projection delocalisee dans la salle.",
    techStack: [],
    achievements: [
      "Projection en pellicule 70mm (6,2 km, 140 kg de bobines)",
      "Installation cabine de projection delocalisee dans la salle au-dessus des spectateurs",
      "Premiere projection publique 70mm au Grand Rex depuis 1989",
      "Accueil et visites de la cabine pour les spectateurs",
    ],
  },
  {
    id: "exp-avatar",
    title: "Assistant projectionniste — Avant-premiere europeenne",
    company: "La Seine Musicale / 20th Century Studios",
    startDate: "decembre 2025",
    endDate: "decembre 2025",
    current: false,
    location: "Boulogne-Billancourt",
    contractType: "PONCTUEL",
    remote: "ONSITE",
    description:
      "Assistant projectionniste et responsable technique pour l'avant-premiere europeenne d'Avatar : De feu et de cendres a La Seine Musicale. Installation de la cabine de projection, branchement du systeme son IMAX, preparation de la venue du public. Evenement en presence de James Cameron.",
    techStack: [],
    achievements: [
      "Installation complete cabine de projection pour avant-premiere europeenne",
      "Configuration systeme son IMAX et calibration image",
      "Coordination technique son et image pour projection evenementielle",
      "Evenement en presence de James Cameron et de l'equipe du film",
    ],
  },
  {
    id: "exp-klesia",
    title: "Developpeur Applications Mobiles React Native",
    company: "KLESIA",
    startDate: "janvier 2025",
    endDate: "",
    current: true,
    location: "Montreuil",
    contractType: "CDI",
    remote: "HYBRID",
    description:
      "Pilote la maintenance et l'evolution d'une application mobile multi-tenant de gestion retraite/prevoyance (React Native 0.77, 100K+ telechargements). Contribue a une architecture Clean/DDD structuree en 22+ modules metier avec un design system de 59+ composants UI. Gere 12 environnements de deploiement (Android Flavors + iOS Schemes) et maintient une suite de 130+ mocks. Refactore du code legacy critique pour ameliorer la stabilite et la maintenabilite.",
    teamContext: "Equipe 3 developpeurs, 100K+ telechargements",
    techStack: [
      "React Native 0.77",
      "React 18",
      "TypeScript 5.6",
      "Redux Toolkit",
      "RxJS",
      "React Navigation v6",
      "Reanimated 3",
      "Jest",
      "React Testing Library",
    ],
    achievements: [
      "Architecture Multi-tenant depuis une base de code unique",
      "22+ modules metier avec separation Domain/Infrastructure/Presentation",
      "59+ composants UI custom",
      "130+ mocks configures",
      "12 environnements de deploiement",
    ],
  },
  {
    id: "exp-ghanem2",
    title: "Developpeur Fullstack React / Next.js",
    company: "Loic Ghanem — V2",
    startDate: "decembre 2025",
    endDate: "decembre 2025",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "REMOTE",
    description:
      "Refonte complete integrale du portfolio de compositeur de musique de films, jeux video et publicites. Ajout de visualisations 3D immersives (Three.js / React Three Fiber), lecteur audio personnalise, cartographie interactive des collaborations mondiales (Mapbox GL), generation de CV PDF, et back-office de gestion de contenu.",
    techStack: [
      "Next.js 16",
      "React 19",
      "Three.js",
      "React Three Fiber",
      "TailwindCSS",
      "Framer Motion",
      "Mapbox GL",
      "Prisma",
      "Better Auth",
    ],
    achievements: [
      "Visualisations 3D immersives avec Three.js / React Three Fiber",
      "Cartographie interactive des collaborations mondiales (Mapbox GL)",
      "Generateur de CV PDF et lecteur audio personnalise",
      "Back-office de gestion de contenu avec editeur Tiptap",
    ],
  },
  {
    id: "exp-jaji",
    title: "Developpeur Applications Mobiles React Native",
    company: "Jaji",
    startDate: "septembre 2023",
    endDate: "janvier 2025",
    current: false,
    location: "Paris",
    contractType: "CDI",
    remote: "HYBRID",
    description:
      "Developpe des fonctionnalites metier cles (remboursements, contrats, beneficiaires, documents) pour une app de mutuelle sante (50K+ telechargements). Structure un design system de 59+ composants reutilisables. Integre le stack Firebase complet (Analytics, Crashlytics, Push Notifications). Contribue activement en equipe Agile/Scrum/SAFe.",
    teamContext: "Equipe 3 developpeurs, 50K+ telechargements",
    techStack: [
      "React Native 0.77",
      "React 18",
      "TypeScript",
      "Redux Toolkit",
      "RxJS",
      "React Navigation v6",
      "i18next",
      "Firebase",
      "Jest",
    ],
    achievements: [
      "59+ composants design system reutilisables",
      "Integration Firebase complete (Analytics, Crashlytics, Push)",
      "State management hybride Redux Toolkit + RxJS BehaviorSubject",
      "Internationalisation multi-langue via i18next",
    ],
  },
  {
    id: "exp-weil",
    title: "Developpeur React / Next.js",
    company: "Weil & Associes",
    startDate: "novembre 2023",
    endDate: "fevrier 2024",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "ONSITE",
    description:
      "Cadre les besoins client et pilote la refonte complete du site d'un cabinet d'avocats parisien (Next.js 13, TailwindCSS). Developpe un back-office de gestion du contenu (equipe, actualites) avec Supabase. Optimise le SEO et les performances pour le secteur juridique.",
    techStack: [
      "Next.js 13",
      "React 18",
      "TailwindCSS",
      "DaisyUI",
      "React Hook Form",
      "Supabase",
      "Nodemailer",
      "i18next",
    ],
    achievements: [
      "Refonte complete du design et direction artistique",
      "Back-office de gestion de contenu",
      "Optimisation SEO et performances",
    ],
  },
  {
    id: "exp-senyk",
    title: "Developpeur Front-End React",
    company: "Caroline Senyk",
    startDate: "octobre 2023",
    endDate: "decembre 2023",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "REMOTE",
    description:
      "Developpement d'un portfolio artistique avec Next.js. Integration d'une galerie photo interactive avec carousel, effets visuels creatifs (water wave), et integration video YouTube. Mise en place d'un CMS integre et d'une internationalisation multi-langues (FR/EN).",
    techStack: [
      "Next.js 16",
      "React 19",
      "Bootstrap 5",
      "SASS",
      "Swiper",
      "Prisma",
      "PostgreSQL",
      "Resend",
      "i18next",
    ],
    achievements: [
      "Galerie photo interactive avec carousel, lightbox et effets visuels (water wave)",
      "Integration video YouTube et animations creatives",
      "CMS integre pour gestion du contenu artistique",
      "Internationalisation multi-langues FR/EN (i18next)",
    ],
  },
  {
    id: "exp-ghanem1",
    title: "Developpeur Front-End React",
    company: "Loic Ghanem — V1",
    startDate: "juillet 2023",
    endDate: "septembre 2023",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "REMOTE",
    description:
      "Creation et fondation du portfolio d'un compositeur de musique pour films, jeux video et publicites. Integration d'un lecteur audio personnalise. Design responsive et animations fluides.",
    techStack: ["Next.js", "React.js", "Bootstrap"],
    achievements: [
      "Portfolio immersif pour compositeur de musique (films, jeux video, publicites)",
      "Lecteur audio personnalise pour les compositions musicales",
      "Design responsive et animations fluides",
      "Navigation intuitive entre les categories de projets",
    ],
  },
  {
    id: "exp-neon",
    title: "Cofondateur & Developpeur React / Next.js",
    company: "Agence Neon",
    startDate: "mars 2023",
    endDate: "janvier 2024",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "ONSITE",
    description:
      "Cofonde et developpe une agence digitale parisienne (equipe de 3 devs). Livre des sites web et applications avec Next.js pour des clients varies. Pilote la gestion de projets en Agile/Scrum. Analyse les donnees Google Analytics pour optimiser les performances et le SEO des projets clients.",
    teamContext: "Equipe 3 developpeurs",
    techStack: [
      "React Native",
      "Next.js",
      "React.js",
      "Bootstrap",
      "Google Analytics",
    ],
    achievements: [
      "Cofondation d'une agence digitale parisienne (equipe de 3 developpeurs)",
      "5+ sites web et applications livres avec Next.js pour des clients varies",
      "Gestion de projets en methodologie Agile/Scrum",
      "Analyse Google Analytics pour optimisation des performances et SEO clients",
    ],
  },
  {
    id: "exp-nip",
    title: "Cofondateur & Developpeur React",
    company: "Nos Instants Precieux",
    startDate: "mars 2023",
    endDate: "septembre 2023",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "ONSITE",
    description:
      "Cofondation et developpement d'un site e-commerce avec Next.js et Bootstrap. Gestion de projet en methodologie Agile avec le client. Mise en place d'une strategie SEO et de strategies marketing pour l'acquisition.",
    techStack: ["Next.js", "React.js", "Bootstrap"],
    achievements: [
      "Cofondation et developpement d'un site e-commerce (Next.js, Bootstrap)",
      "Gestion de projet en methodologie Agile avec le client sur 6 mois",
      "Mise en place d'une strategie SEO pour le referencement naturel",
      "Strategies marketing pour l'acquisition de trafic",
    ],
  },
  {
    id: "exp-crazee",
    title: "Developpeur React",
    company: "Crazee Burger",
    startDate: "avril 2023",
    endDate: "juin 2023",
    current: false,
    location: "Paris",
    contractType: "PONCTUEL",
    remote: "ONSITE",
    description:
      "Developpement d'un MVP de commande en ligne avec gestion des menus et panier. Interface utilisateur reactive avec React.js et Firebase comme backend.",
    techStack: ["React.js", "Firebase", "Styled Components", "React Router"],
    achievements: [
      "MVP de commande en ligne livre en 6 semaines (gestion menus et panier)",
      "Backend Firebase Realtime (Firestore, Authentication)",
      "Interface restaurateur pour gestion des menus en autonomie",
      "Routage client complet avec React Router",
    ],
  },
  {
    id: "exp-mailcert",
    title: "Developpeur Front-End React",
    company: "Mail Certificate",
    startDate: "fevrier 2023",
    endDate: "mai 2023",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "REMOTE",
    description:
      "Livre le front-end et le back-office d'une plateforme SaaS B2B de courriers recommandes certifies. Integre le systeme de paiement Stripe (credits et abonnements) et la double authentification 2FA via Twilio (SMS/email). Developpe un editeur WYSIWYG (Draft.js) pour la composition de courriers.",
    teamContext: "Equipe 2 developpeurs",
    techStack: [
      "React 16",
      "Bootstrap 4",
      "Reactstrap",
      "Styled Components",
      "Draft.js",
      "Node.js",
      "Express.js",
      "Stripe",
      "Twilio",
    ],
    achievements: [
      "Integration Stripe (credits et abonnements)",
      "Double authentification 2FA via Twilio",
      "Editeur WYSIWYG Draft.js",
    ],
  },
  {
    id: "exp-testride",
    title: "Developpeur React Native",
    company: "Test & Ride",
    startDate: "fevrier 2023",
    endDate: "mars 2023",
    current: false,
    location: "Paris",
    contractType: "FREELANCE",
    remote: "REMOTE",
    description:
      "Developpe une application mobile de test de vehicules (React Native, Expo) atteignant 10K+ telechargements. Implemente le backend avec Node.js/Express.js et MongoDB. Integre 4 APIs tierces (Airtable, Google Maps, Api.gouv, Cloudinary) pour enrichir l'experience utilisateur.",
    teamContext: "Equipe 2 developpeurs, 10K+ telechargements",
    techStack: [
      "React Native",
      "Redux Toolkit",
      "Expo",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
    achievements: [
      "10K+ telechargements",
      "Integration 4 APIs tierces (Airtable, Google Maps, Api.gouv, Cloudinary)",
    ],
  },
  {
    id: "exp-cyclofix",
    title: "Responsable des operations",
    company: "Cyclofix (Roulez Jeunesse)",
    startDate: "mai 2016",
    endDate: "aout 2022",
    current: false,
    location: "Paris",
    contractType: "CDI",
    remote: "ONSITE",
    description:
      "Pilote la croissance operationnelle d'une scale-up leader de la reparation velo a domicile pendant 6 ans. Recrute et onboarde 1000+ travailleurs independants a l'echelle nationale. Negocie et gere des partenariats B2B strategiques avec Netflix, Amazon Prime et Canal+. Concoit un entonnoir d'acquisition automatise (Zapier/Airtable) qui optimise le pipeline de recrutement. Manage des equipes larges et dispersees geographiquement avec suivi de KPIs operationnels.",
    techStack: ["Zapier", "Airtable", "Google Analytics"],
    achievements: [
      "1000+ travailleurs independants recrutes et onboardes",
      "Partenariats B2B Netflix, Amazon Prime, Canal+",
      "Entonnoir d'acquisition automatise (Zapier/Airtable)",
      "6 ans de croissance operationnelle",
    ],
  },
  {
    id: "exp-courrier",
    title: "Regulateur Dispatch & Coursier velo",
    company: "Courrier",
    startDate: "janvier 2014",
    endDate: "mai 2016",
    current: false,
    location: "Paris",
    contractType: "CDI",
    remote: "ONSITE",
    description:
      "Regulation et dispatch des coursiers pour les livraisons urbaines a velo. Coordination logistique et optimisation des tournees. Experience terrain en tant que coursier a velo.",
    techStack: [],
    achievements: [
      "Optimisation des tournees pour 30+ coursiers velo en temps reel",
      "Regulation et dispatch des livraisons urbaines",
      "Formation et integration des nouveaux coursiers",
      "Gestion des incidents et resolution de problemes sous pression",
    ],
  },
  {
    id: "exp-ourtheory",
    title: "Musicien / Bassiste professionnel",
    company: "Our Theory",
    startDate: "juin 2010",
    endDate: "aout 2016",
    current: false,
    location: "France, Europe, US",
    contractType: "HORS_TECH",
    remote: "ONSITE",
    description:
      "Bassiste professionnel au sein d'un groupe en tournee internationale (France, Europe, US) avec distribution mondiale. Gere la logistique de tournee, coordonne les equipes techniques et developpe une resilience sous pression en conditions live.",
    techStack: [],
    achievements: [
      "Tournees internationales France, Europe, US (dont SXSW)",
      "Distribution mondiale et presence sur les plateformes de streaming",
      "Gestion logistique de tournee (plannings, equipements, transports)",
      "Coordination des equipes techniques en conditions live",
    ],
  },
  {
    id: "exp-bagel",
    title: "Regisseur",
    company: "Studio Bagel / Canal Plus",
    startDate: "2009",
    endDate: "2010",
    current: false,
    location: "Region parisienne",
    contractType: "HORS_TECH",
    remote: "ONSITE",
    description:
      "Regie de plateau pour des productions audiovisuelles (Studio Bagel / Canal+). Coordination des equipes techniques, gestion logistique des tournages, respect des plannings de production.",
    techStack: [],
    achievements: [
      "Regie de plateau pour 20+ tournages audiovisuels (Studio Bagel / Canal+)",
      "Coordination des equipes techniques sur les tournages",
      "Gestion logistique des tournages et respect des plannings de production",
      "Interface entre production et direction artistique",
    ],
  },
  {
    id: "exp-ugc",
    title: "Operateur Projectionniste",
    company: "UGC / CGR",
    startDate: "2004",
    endDate: "2008",
    current: false,
    location: "France",
    contractType: "HORS_TECH",
    remote: "ONSITE",
    description:
      "Operation et maintenance des equipements de projection cinematographique. Gestion des seances et coordination avec les equipes de salle.",
    techStack: [],
    achievements: [
      "Operation et maintenance des equipements de projection 35mm et numerique",
      "Gestion multi-salles avec coordination des seances",
      "Formation et accompagnement des operateurs juniors",
      "CAP Operateur Projectionniste obtenu en 2009",
    ],
  },
];

// --- 7 Projets ---

export const SEED_PROJECTS: MasterCvProject[] = [
  {
    id: "proj-jobio",
    name: "Jobio",
    description:
      "CRM de prospection freelance qui centralise la gestion des missions, profils, plateformes et contacts. Tableau Kanban drag & drop avec 8 statuts. Assistant IA pour generer des candidatures et auditer les profils LinkedIn. CV Lab IA pour creer des CV sur mesure par mission. Systeme de sequences automatisees de relance. Abonnement Stripe avec 3 plans.",
    url: "https://jobio.fr",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Zustand",
      "TanStack Query",
      "Recharts",
      "Prisma ORM 6.16",
      "Better Auth",
      "Stripe",
      "OpenAI SDK",
      "PostgreSQL",
      "Redis",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "CV Lab IA avec 4 templates",
      "Assistant IA candidature",
      "Kanban drag & drop 8 statuts",
      "Stripe 3 plans",
    ],
  },
  {
    id: "proj-impulsion",
    name: "Impulsion",
    description:
      "Plateforme hybride connectant coachs et athletes. Planification de seances avec calendrier drag & drop. Annotation de videos. Calcul de charge d'entrainement (ACWR). Suivi de progression en temps reel. Visualisations 3D immersives.",
    url: "https://impulsion.app",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Three.js",
      "React Three Fiber",
      "Recharts",
      "Prisma ORM 6.19",
      "Better Auth",
      "Stripe",
      "OpenAI SDK",
      "PostgreSQL",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "Visualisations 3D immersives",
      "Calcul de charge ACWR",
      "Annotation video",
    ],
  },
  {
    id: "proj-hyrun",
    name: "Hyrun",
    description:
      "Coach personnel IA pour athletes hybrides (HYROX & running). Plans d'entrainement intelligents avec gestion des phases. Substitutions d'exercices selon l'equipement. Calendrier unifie avec logs detailles. Plans nutritionnels personnalises par IA.",
    url: "https://hyrun.app",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Zustand",
      "TanStack Query",
      "Recharts",
      "Prisma ORM 6.16",
      "Better Auth",
      "Stripe",
      "OpenAI SDK",
      "PostgreSQL",
      "Redis",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "Coach IA personnalise",
      "Plans nutritionnels IA",
      "Benchmarks running (5K, 10K, semi, marathon)",
    ],
  },
  {
    id: "proj-eggscuseme",
    name: "EggscuseMe",
    description:
      "Application web pour gerer la fraicheur des oeufs et eviter le gaspillage alimentaire. Scanner IA (Google Gemini Vision) pour extraction automatique des dates de ponte. PWA complete avec Service Worker et Push Notifications. Systeme de partage multi-frigo.",
    url: "https://eggscuseme.app",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Zustand",
      "TanStack Query",
      "Prisma ORM 6.16",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "Scanner IA Gemini Vision",
      "PWA complete avec Push Notifications",
      "Partage multi-frigo",
    ],
  },
  {
    id: "proj-mycryptopilot",
    name: "MyCryptoPilot",
    description:
      "Plateforme de trading social risk-first permettant de suivre des traders verifies, recevoir leurs signaux en temps reel et consulter des performances verifiees via APIs Binance & Bybit. Bot Discord 24/7 sur Fly.io.",
    url: "https://mycryptopilot.app",
    technologies: [
      "Next.js 15",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Recharts",
      "Prisma ORM 6.15",
      "Better Auth",
      "BullMQ",
      "Discord.js 14",
      "ccxt",
      "PostgreSQL",
      "Redis",
      "Docker",
      "Fly.io",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "Bot Discord 24/7 sur Fly.io",
      "Paiements crypto natifs (Base/Tron)",
      "21 suites Vitest, 26 specs Playwright",
    ],
  },
  {
    id: "proj-moodday",
    name: "MoodDay",
    description:
      "Compagnon digital concu avec des psychiatres pour mieux comprendre ses humeurs, suivre ses traitements et preparer ses consultations. Conforme RGPD avec donnees chiffrees. Export PDF medical.",
    url: "https://moodday.app",
    technologies: [
      "Next.js 16",
      "React 19",
      "TypeScript 5.9",
      "TailwindCSS v4",
      "Shadcn/UI",
      "Recharts",
      "Prisma ORM",
      "Better Auth",
      "Resend",
      "jsPDF",
      "PostgreSQL",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2025",
    endDate: "",
    status: "En cours",
    highlights: [
      "Concu avec des psychiatres",
      "Conforme RGPD, donnees chiffrees",
      "Export PDF medical",
    ],
  },
  {
    id: "proj-homego",
    name: "HomeGo",
    description:
      "Plateforme immobiliere pour investir intelligemment. Agregation d'annonces. Analyse des prix via donnees DVF certifiees. Negociation assistee par IA. Simulateur de capacite d'emprunt.",
    technologies: [
      "Next.js 15",
      "React 19",
      "TypeScript 5.8",
      "TailwindCSS v4",
      "Mapbox GL",
      "Recharts",
      "Prisma ORM 6.12",
      "Better Auth",
      "Stripe",
      "OpenAI SDK",
      "PostgreSQL",
      "Vitest",
      "Playwright",
    ],
    role: "Solo developer",
    startDate: "2024",
    endDate: "",
    status: "Termine",
    highlights: [
      "Donnees DVF certifiees",
      "Negociation assistee par IA",
      "Simulateur emprunt",
    ],
  },
];

// --- 6 Formations ---

export const SEED_EDUCATION: MasterCvEducation[] = [
  {
    id: "edu-capsule",
    institution: "La Capsule",
    degree: "Chef de Projet Web et Mobile",
    field: "Developpement Web et Mobile",
    startDate: "decembre 2022",
    endDate: "mars 2023",
    description: "RNCP Niveau 6",
  },
  {
    id: "edu-openclassrooms",
    institution: "OpenClassrooms",
    degree: "Developpeur Web Fullstack JS React",
    field: "Developpement Web",
    startDate: "aout 2022",
    endDate: "decembre 2022",
    description: "Formation professionnelle",
  },
  {
    id: "edu-codecademy",
    institution: "Codecademy",
    degree: "Full-Stack Software Engineer",
    field: "Developpement Web",
    startDate: "aout 2022",
    endDate: "decembre 2022",
    description: "Autoformation",
  },
  {
    id: "edu-freecodecamp",
    institution: "freeCodeCamp",
    degree: "Full-Stack Software Engineer",
    field: "Developpement Web",
    startDate: "septembre 2022",
    endDate: "decembre 2022",
    description: "Autoformation",
  },
  {
    id: "edu-paris8",
    institution: "Universite Paris 8",
    degree: "Licence Art du Spectacle Cinematographique",
    field: "Cinema",
    startDate: "septembre 2009",
    endDate: "mai 2011",
  },
  {
    id: "edu-cap",
    institution: "Candidat libre",
    degree: "CAP Operateur Projectionniste",
    field: "Projection cinematographique",
    startDate: "2009",
    endDate: "2009",
  },
];

// --- Skills ---

export const SEED_SKILLS: MasterCvSkill[] = [
  // Core
  { id: "sk-rn", name: "React Native", level: "EXPERT" },
  { id: "sk-react", name: "React", level: "EXPERT" },
  { id: "sk-nextjs", name: "Next.js", level: "EXPERT" },
  { id: "sk-ts", name: "TypeScript", level: "EXPERT" },
  // Frontend
  { id: "sk-tw", name: "TailwindCSS v4", level: "ADVANCED" },
  { id: "sk-shadcn", name: "Shadcn/UI", level: "ADVANCED" },
  { id: "sk-redux", name: "Redux Toolkit", level: "ADVANCED" },
  { id: "sk-zustand", name: "Zustand", level: "ADVANCED" },
  { id: "sk-rxjs", name: "RxJS", level: "ADVANCED" },
  { id: "sk-tanstack", name: "TanStack Query", level: "ADVANCED" },
  { id: "sk-threejs", name: "Three.js", level: "INTERMEDIATE" },
  { id: "sk-recharts", name: "Recharts", level: "ADVANCED" },
  { id: "sk-motion", name: "Motion / Framer Motion", level: "ADVANCED" },
  // Backend
  { id: "sk-node", name: "Node.js", level: "ADVANCED" },
  { id: "sk-express", name: "Express.js", level: "ADVANCED" },
  { id: "sk-prisma", name: "Prisma ORM", level: "EXPERT" },
  { id: "sk-pg", name: "PostgreSQL", level: "ADVANCED" },
  { id: "sk-mongo", name: "MongoDB", level: "INTERMEDIATE" },
  { id: "sk-firebase", name: "Firebase", level: "ADVANCED" },
  { id: "sk-redis", name: "Redis", level: "ADVANCED" },
  // Auth & Paiement
  { id: "sk-betterauth", name: "Better Auth", level: "ADVANCED" },
  { id: "sk-stripe", name: "Stripe", level: "ADVANCED" },
  // IA
  { id: "sk-openai", name: "OpenAI SDK (Vercel AI)", level: "ADVANCED" },
  { id: "sk-gemini", name: "Google Gemini Vision", level: "INTERMEDIATE" },
  // DevOps
  { id: "sk-vercel", name: "Vercel", level: "ADVANCED" },
  { id: "sk-docker", name: "Docker", level: "INTERMEDIATE" },
  { id: "sk-ghactions", name: "GitHub Actions CI/CD", level: "ADVANCED" },
  { id: "sk-expo", name: "Expo", level: "ADVANCED" },
  // Testing
  { id: "sk-vitest", name: "Vitest", level: "ADVANCED" },
  { id: "sk-playwright", name: "Playwright", level: "ADVANCED" },
  { id: "sk-jest", name: "Jest", level: "ADVANCED" },
];

// --- Langues ---

export const SEED_LANGUAGES: MasterCvLanguage[] = [
  { id: "lang-fr", name: "Francais", level: "Natif (C2)" },
  { id: "lang-en", name: "Anglais", level: "Professionnel" },
];

// --- Certifications ---

export const SEED_CERTIFICATIONS: MasterCvCertification[] = [];
